### ISSUE TITLE
Feature request / Lack of understanding

### ISSUE THREAD

**Issue by Muffexx** [MMRIZE/MMM-CalendarExt3Timeline#6]
Hello there.

I love this module and have been using it since many months!
There are, since one of the more recent updates, some changes, I would like to "alter".

![image](https://github.com/MMRIZE/MMM-CalendarExt3Timeline/assets/33467400/8c2b75a9-570b-4afd-a3ac-aebde2237a1d)

1. Can start times of multi-day events be removed?
2. Can end times of multi-day events be removed?
3. Can start times of full-day events be removed?

The numbers correspond to the numbers in the picture.

regards
Muffexx

**Comment by eouia** [comment]
1. Your question is not about MMM-CalendarExt3Timeline, It was MMM-CalendarExt3
2. To remove Multi-day event's time; append these into your `css/custom.css`
```css
.CX3 .event.multiday .headline .time.endTime,
.CX3 .event.multiday .headline .time.startTime {
  display: none;
}
```
<img width="464" alt="image" src="https://github.com/MMRIZE/MMM-CalendarExt3Timeline/assets/1720610/2be01e3b-b31a-4f0a-8f7c-06420c5cebf4">


3. Fullday event doesn't show start/end time. I think you may confuse multiday event.
